let score=(prompt=parseInt);
if(score [100]&[90]){
console.log("voto ottimo")
}else if([70]&[89])
{console.log("voto buono")}
else if([60]&[69])
    {console.log("voto sufficiente")}
else if([0]&[59])
    {console.log("voto insufficiente")}
